---
language: ruby
bundler_args: --without development acceptance
cache: bundler
branches:
  only:
    - master
before_install: rm Gemfile.lock || true
sudo: false
script:
  - "bundle exec rake lint"
  - "bundle exec rake syntax"
  - "bundle exec rake spec SPEC_OPTS='--format documentation'"
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.4.5
env:
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 3.5.1"
  - PUPPET_VERSION="~> 3.6.0"
  - PUPPET_VERSION="~> 3.7.0"
  - PUPPET_VERSION="~> 4.0.0"
  - PUPPET_VERSION="~> 5.5.0"

global:
  - PUBLISHER_LOGIN=abrader

notifications:
  email: false
